import config, os
from Core import Utils

class Plugin(object):
    """ Configures everything needed for Debian APT. """
    parameterHook = "--apt"
    parameterDescription = "Reconfigure APT on Debian"
    parameterArgs = ""
    autoRun = False
    required = "debian"
    configFiles = [ 
        "/etc/apt/sources.list",
    ]

    def reloadServices(self):
        #os.system('aptitude update')
        pass

    def writeConfig(self, *a):  
        l = open('/etc/apt/sources.list', 'wt')
        l.write('# Generated by TUMS Configurator \n\n')

        if config.General.get('aptprimary', None) and 'vulani' not in config.General.get('aptprimary',"").lower() and 'synergia.thusa.net' not in config.General.get('aptprimary',"").lower(): #APPLY sanity
            if config.General['aptprimary'].split()[0] != "deb": #For special people who forget deb
                l.write("deb " + config.General['aptprimary'] + ' lenny main contrib\n')
            else:
                l.write(config.General['aptprimary'] + ' lenny main contrib\n')
        else:
            l.write('deb http://debian.mirror.ac.za/debian/ lenny main contrib\n')

        l.write('deb http://debian.vulani.net/debian/ lenny main\n')

        l.write('deb-src http://ftp.us.debian.org/debian lenny main\n')

        l.write('deb http://volatile.debian.org/debian-volatile lenny/volatile main contrib non-free\n')

        l.write('deb http://security.debian.org/ lenny/updates main\n')
        l.write('deb-src http://security.debian.org/ lenny/updates main\n')

        l.close()
