import config, os
from Core import Utils

class Plugin(object):
    """ Configures everything needed for Open NTPD """
    parameterHook = "--ntp"
    parameterDescription = "Reconfigure OpenNTP"
    parameterArgs = ""
    autoRun = False
    required = "debian"
    configFiles = [ 
        "/etc/openntpd/ntpd.conf",
    ]

    def reloadServices(self):
        os.system('/etc/init.d/openntpd restart')

    def writeConfig(self, *a):  
        conf = """# Generated by Vulani
listen on *

server pool.ntp.org
server 0.debian.pool.ntp.org
server 1.debian.pool.ntp.org
server 2.debian.pool.ntp.org
server 3.debian.pool.ntp.org\n"""


        l = open('/etc/openntpd/ntpd.conf', 'wt')
        l.write(conf)
        l.close()
