import config, os
from Core import Utils
import socket, struct

class Plugin(object):
    parameterHook = "--debnet"
    parameterDescription = "Reconfigure Debian network"
    parameterArgs = ""
    autoRun = True
    required = "debian"
    configFiles = [ 
        "/etc/network/interfaces",
    ]

    def reloadServices(self):
        pass

    def cidr2netmask(self, cidr):
        return socket.inet_ntoa(struct.pack('<L', socket.htonl(0xffffffff - ((1 << (32-cidr)) -1 ))))

    def PPPoEBuilder(self, unit, device, username, password, default=False):
        """
        @param unit: PPP unit number
        @param device: Ethernet PAC bridge device
        @param username: Username for PPPoE connection
        @param password: Password for PPPoE connection
        @param default: Use this as default route
        """
        peerConfig = """noipdefault
hide-password
lcp-echo-interval 30
lcp-echo-failure 4
noauth
persist
mtu 1492
persist
maxfail 0
holdoff 20
plugin rp-pppoe.so %s
user "%s"
unit %s\n""" % (device, username, unit)
        if default:
            peerConfig += "defaultroute\nreplacedefaultroute\n"

        l = open('/etc/ppp/peers/wan%s' % unit, 'wt')
        l.write(peerConfig)
        l.close()

        pap = open('/etc/ppp/pap-secrets', 'at')
        chap = open('/etc/ppp/chap-secrets', 'at')
        passLine = '"%s"   *   "%s"\n' % (username, password)
        pap.write(passLine)
        chap.write(passLine)
        pap.close()
        chap.close()

        return "auto wan%s\niface wan%s inet ppp\nprovider wan%s\n  pre-up /sbin/ifconfig %s up\n" % (unit, unit, unit, device)

    def vlanBuilder(self, i, defn):
        iface = {
            'ip': defn['ip'].split('/')[0],
            'vnum': i.replace('vlan',''),
            'network': defn['network'].split('/')[0],
            'netmask': Utils.cidr2netmask(defn['ip'].split('/')[-1]),
            'interface': defn['interface']
        }
        ifacedef = """auto vlan%(vnum)s
iface vlan%(vnum)s inet static
address %(ip)s
netmask %(netmask)s
network %(network)s
vlan_raw_device %(interface)s\n\n""" % iface
        return ifacedef

    def writeConfig(self, *a):
        # We must ALWAYS have a loopback defenition or else lots of shit breaks quite horribly
        net = "# Generated by TUMS Configurator\nauto lo\niface lo inet loopback\n\n" 
        dhcpifaces = []
        for interface, defin in config.EthernetDevices.items():
            if interface != "extra" and "vlan" not in interface:
                net += "auto %s\niface %s inet " % (interface, interface)
                
                if defin['type'].lower() == 'dhcp':
                    net += 'dhcp\n'
                elif defin['type'].lower() == 'manual':
                    net += 'manual\n'
                else:
                    ip, cidr = tuple(defin['ip'].split('/'))
                    net += 'static\n'
                    net += '  address %s\n' % ip
                    net += '  netmask %s\n' % self.cidr2netmask(int(cidr))
                    if interface == config.LANPrimary and config.Tunnel.get('ipv6', False):
                        remote = config.Tunnel['ipv6']['remoteip']
                        local = config.Tunnel['ipv6']['localip']
                        localv6 = config.Tunnel['ipv6']['localv6']
                        net+= '  up ip tunnel add ipv6tun mode sit remote %s local %s ttl 255' % (remote, local)
                        net+= '  up ip link set ipv6tun up'
                        net+= '  up ip addr add %s dev ipv6tun' % (localv6) 
                        net+= '  up ip -6 ro add 2003::/3 dev ipv6tun'

                # aliases (use ip ro on post-up conditions)
                if defin.get('aliases', None):
                    for alias in defin['aliases']:
                        net += '  up   ip addr add %s dev %s\n' % (alias, interface)
                
                # check routes - add to Zebra (separate plugin) if not a default
                if defin.get('routes', None):
                    for dest, gw in defin['routes']:
                        if dest=='default':
                            net += '  gateway %s\n' % gw
                if defin.get('extra', None):
                    net += defin['extra'] + '\n'
                net += '\n'

            if "vlan" in interface:
                net += self.vlanBuilder(interface, defin)

            if interface == config.LANPrimary:
                dhcpifaces.append(interface)
            elif defin.get('dhcpserver', False):
                dhcpifaces.append(interface)

        dhcpconf = """# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#       Separate multiple interfaces with spaces, e.g. "eth0 eth1".
INTERFACES="%s"\n""" % (' '.join(dhcpifaces))

        d3serv = open('/etc/default/dhcp3-server', 'wt')
        d3serv.write(dhcpconf)
        d3serv.close()

        if config.EthernetDevices.get('extra', None):
            net += config.EthernetDevices['extra']
            net += '\n'

        for interface, defin in config.WANDevices.items():
            if interface != "extra":
                unit = interface.strip('ppp')
                default = False
                if 'defaultroute' in  defin['pppd']:
                    default = True
                net += self.PPPoEBuilder(unit, defin['link'], defin['username'], defin['password'], default)

        if config.WANDevices.get('extra', None):
            net += config.WANDevices['extra']
            net += '\n'

        netConf = open('/etc/network/interfaces', 'wt')
        netConf.write(net)
        netConf.close()
