#!/usr/bin/python

import os, sys
unit = sys.argv[1]

running = os.popen('ps aux | grep "pppd call wan%s" | grep -v grep | awk \'{print $2}\'' % unit).read().strip('\n')

os.system('poff wan%s' % unit)

for i in running.split('\n'):
    os.system('kill -9 %s' % i)
