# This should go into a separate file since it should be standardised to that Vulani image...
import config

StandardFiles = {
       'files'    : [
            ('samba.schema',        '/etc/ldap/schema/samba.schema'),
            ('thusa.schema',        '/etc/ldap/schema/thusa.schema'),
            ('fetchmailrc',         '/etc/fetchmailrc'),
            ('STARTUP.BAT',         '/var/lib/samba/netlogon/STARTUP.BAT'),
            ('smartd.conf',         '/etc/smartd.conf'),
            ('01_default_mail.conf-debian','/etc/apache2/sites-enabled/01_default_mail.conf'),
            ('000-default',         '/etc/apache2/sites-available/default'),
            ('authldaprc',          '/etc/courier/authldaprc'),
            ('authdaemonrc',        '/etc/courier/authdaemonrc'),
            ('cupsd.conf',          '/etc/cups/cupsd.conf'),
            ('tums.cron',           '/etc/cron.d/tums'),
            ('etrn_script',         '/etc/exim4/etrn_script'),
            ('hubbed_hosts',        '/etc/exim4/hubbed_hosts'),
            ('local_domains',       '/etc/exim4/local_domains'),
            ('ldap.conf',           '/etc/ldap/ldap.conf'),
            ('deb-slapd.conf',      '/etc/ldap/slapd.conf'),
            ('smbldap.conf',        '/etc/smbldap-tools/smbldap.conf'),
            ('smbldap_bind.conf',   '/etc/smbldap-tools/smbldap_bind.conf'),
            ('shorewall.conf',      '/etc/shorewall/shorewall.conf'),
            ('params',              '/etc/shorewall/params'),
            ('clamd.conf',          '/etc/clamav/clamd.conf'),
            ('freshclam.conf',      '/etc/clamav/freshclam.conf'),
            ('resolv.conf',         '/etc/resolv.conf'),
            ('ldap_import.sh',      '/usr/local/tcs/tums/ldap_import.sh'),
            ('bash.bashrc',         '/etc/bash.bashrc'),
            ('bash.bashrc',         '/root/.bashrc'),
            ('profile',             '/etc/profile'),
            ('vimrc',               '/root/.vimrc'),
            ('ulogd.conf',          '/etc/ulogd.conf'),
            ('default-ddclient',    '/etc/default/ddclient'),
            ('default-smartmontools', '/etc/default/smartmontools'),
            ('greylist-config',     '/etc/greylistd/config'),
            #('lts.conf',            '/opt/ltsp-4.1/i386/etc/lts.conf'),
        ],
        'replacers'    : [
            ('bpexample.com',           config.Domain),
            ('BPEXAMPLE',               config.LDAPBase),
            ('BPDOMAIN',                config.SambaDomain),
            ('wsbpexample',             config.LDAPPassword),
            ('dc=bpexample,dc=com',     ','.join(["dc=%s" % i for i in config.Domain.split('.')])), 
            ('bpexample.Friendly',      config.CompanyName),
            ('bpexample.forwarders',    ''.join(['\t%s;\n' % i for i in config.ForwardingNameservers])), 
            ('bpexample.ntpaddr',       config.NTP),
            ('bpexample.smtprelay',     config.SMTPRelay),
            ('bpexample.hostname',      config.Hostname),
            ('bpexample.ddns_email',    "notify@thusa.co.za"), 
            ('bpexample.ddns_user',     config.ThusaDNSUsername),
            ('bpexample.ddns_pass',     config.ThusaDNSPassword),
            ('bpexample.ddns_addr',     config.ThusaDNSAddress),
            ('bpexample.net_dev',       config.WANPrimary),
            ('bplocal_domains',         '\n'.join(config.LocalDomains)),
            ('root@newdom.co.za',       'notify@thusa.co.za'),
        ]    
    }
