# This should go into a separate file since it should be standardised to that Vulani image...
import config

netOctets = '.'.join(config.EthernetDevices[config.LANPrimary[0]]['network'].split('.')[:3])

StandardFiles = {
       'files'    : [
            ('exports',             '/etc/exports'),
            ('fetchmailrc',         '/etc/fetchmailrc'),
            ('STARTUP.BAT',         '/var/lib/samba/netlogon/STARTUP.BAT'),
            ('hosts',               '/etc/hosts'),
            ('make.conf',           '/etc/make.conf'),
            ('ntp.conf',            '/etc/ntp.conf'),
            ('resolv.conf',         '/etc/resolv.conf'),
            ('smartd.conf',         '/etc/smartd.conf'),
            ('01_default_mail.conf','/etc/apache2/vhosts.d/01_default_mail.conf'),
            ('domainname',          '/etc/conf.d/domainname'),
            ('hostname',            '/etc/conf.d/hostname'),
            ('ntp-client',          '/etc/conf.d/ntp-client'),
            ('authldaprc',          '/etc/courier/authlib/authldaprc'),
            ('cupsd.conf',          '/etc/cups/cupsd.conf'),
            ('hubbed_hosts',        '/etc/exim/hubbed_hosts'),
            ('local_domains',       '/etc/exim/local_domains'),
            ('ldap.conf',           '/etc/openldap/ldap.conf'),
            ('slapd.conf',          '/etc/openldap/slapd.conf'),
            ('options.server',      '/etc/ppp/options.server'),
            ('smbldap.conf',        '/etc/smbldap-tools/smbldap.conf'),
            ('smbldap_bind.conf',   '/etc/smbldap-tools/smbldap_bind.conf'),
            ('etc-ldap.conf',       '/etc/ldap.conf'),
            ('nsswitch.conf',       '/etc/nsswitch.conf'),
            ('ldap.secret',         '/etc/ldap.secret'),
            ('system-auth',         '/etc/pam.d/system-auth'),
            ('accounting',          '/etc/shorewall/accounting'),
            ('scavr.conf',          '/etc/squid/scavr.conf'),
            ('ldap_import.sh',      '/usr/local/tcs/tums/ldap_import.sh'),
            #('lts.conf',            '/opt/ltsp-4.1/i386/etc/lts.conf'),
        ],
        'replacers'    : [
            ('bpexample.com',           config.Domain),
            ('BPEXAMPLE',               config.LDAPBase),
            ('BPDOMAIN',                config.SambaDomain),
            ('wsbpexample',             config.LDAPPassword),
            ('dc=bpexample,dc=com',     ','.join(["dc=%s" % i for i in config.Domain.split('.')])), 
            ('bpexample.Friendly',      config.CompanyName),
            ('bpexample.forwarders',    ''.join(['\t%s;\n' % i for i in config.ForwardingNameservers])), 
            ('bpexample.ntpaddr',       config.NTP),
            ('bpexample.smtprelay',     config.SMTPRelay),
            ('bpexample.hostname',      config.Hostname),
            ('bpexample.ddns_email',    "notify@thusa.co.za"), 
            ('bpexample.ddns_user',     config.ThusaDNSUsername),
            ('bpexample.ddns_pass',     config.ThusaDNSPassword),
            ('bpexample.ddns_addr',     config.ThusaDNSAddress),
            ('bpexample.lan_dev',       config.LANPrimary), 
            ('bpexample.net_dev',       config.WANPrimary),
            ('bplocal_domains',         '\n'.join(config.LocalDomains)),
            ('192.168.0',               netOctets),
            ('0.168.192.in-addr.arpa',  "%s.in-addr.arpa" % '.'.join([i for i in reversed(netOctets.split('.'))])),
            ('root@newdom.co.za',       'notify@thusa.co.za'),
        ]    
    }
